import type { Product } from './types'

/** Przykladowe produkty (dane mockowe; 7 pozycji jak w projekcie Figma, 2 strony po 5). */
export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p-1',
    name: 'MacBook Pro 14"',
    sku: 'MBP14M3PRO',
    description: '',
    manufacturer: 'apple',
    category: 'komputery',
    features: ['wifi', 'bluetooth', 'usb-c', 'premium'],
    netPrice: 8129.27,
    grossPrice: 9999,
    vatRate: 23,
    currency: 'PLN',
    isAvailable: true,
    isLimited: false,
    stock: null,
    minCartQty: 1,
    maxCartQty: 5,
  },
  {
    id: 'p-2',
    name: 'Galaxy S24 Ultra',
    sku: 'SGS24U256',
    description: '',
    manufacturer: 'samsung',
    category: 'telefony',
    features: ['wifi', 'bluetooth', 'usb-c', 'waterproof'],
    netPrice: 5121.14,
    grossPrice: 6299,
    vatRate: 23,
    currency: 'PLN',
    isAvailable: true,
    isLimited: true,
    stock: 45,
    minCartQty: 1,
    maxCartQty: 3,
  },
  {
    id: 'p-3',
    name: 'Sony WH-1000XM5',
    sku: 'SNWH1000XM5',
    description: '',
    manufacturer: 'sony',
    category: 'rtv',
    features: ['bluetooth', 'wireless', 'usb-c'],
    netPrice: 1300,
    grossPrice: 1599,
    vatRate: 23,
    currency: 'PLN',
    isAvailable: true,
    isLimited: false,
    stock: null,
    minCartQty: 1,
    maxCartQty: 10,
  },
  {
    id: 'p-4',
    name: 'Bosch Serie 6 WAU28P40',
    sku: 'BSWAU28P40',
    description: '',
    manufacturer: 'bosch',
    category: 'agd',
    features: ['eco', 'wifi'],
    netPrice: 2682.11,
    grossPrice: 3299,
    vatRate: 23,
    currency: 'PLN',
    isAvailable: false,
    isLimited: true,
    stock: 0,
    minCartQty: 1,
    maxCartQty: 1,
  },
  {
    id: 'p-5',
    name: 'Xiaomi Smart Band 8',
    sku: 'XMSB8BLK',
    description: '',
    manufacturer: 'xiaomi',
    category: 'akcesoria',
    features: ['bluetooth', 'waterproof', 'wireless'],
    netPrice: 145.53,
    grossPrice: 179,
    vatRate: 23,
    currency: 'PLN',
    isAvailable: true,
    isLimited: false,
    stock: null,
    minCartQty: 1,
    maxCartQty: 10,
  },
  {
    id: 'p-6',
    name: 'LG OLED evo C4 55"',
    sku: 'LGOLED55C4',
    description: '',
    manufacturer: 'lg',
    category: 'rtv',
    features: ['wifi', 'bluetooth'],
    netPrice: 3657.72,
    grossPrice: 4499,
    vatRate: 23,
    currency: 'PLN',
    isAvailable: true,
    isLimited: true,
    stock: 12,
    minCartQty: 1,
    maxCartQty: 2,
  },
  {
    id: 'p-7',
    name: 'Lenovo ThinkPad X1 Carbon Gen 12',
    sku: 'LNTPX1G12',
    description: '',
    manufacturer: 'lenovo',
    category: 'komputery',
    features: ['wifi', 'bluetooth', 'usb-c', 'premium'],
    netPrice: 6747.15,
    grossPrice: 8299,
    vatRate: 23,
    currency: 'PLN',
    isAvailable: true,
    isLimited: false,
    stock: null,
    minCartQty: 1,
    maxCartQty: 5,
  },
]
